### ISSUE TITLE
Getting wrong landamrks with each config file

### ISSUE THREAD

**Issue by Nibenitez** [RasmusRPaulsen/Deep-MVLM#12]
Hi!
Thank you for sharing your great work with the community.
I would like to ask wich config file should I use for the model below, I tried geometry and depth, but without sucess. Is it something wrong with my mesh? Thank you.

![image](https://github.com/RasmusRPaulsen/Deep-MVLM/assets/51408311/bac980aa-ca46-46be-a70a-6feec7c74af2)

**Comment by RasmusRPaulsen** [comment]
Hi,

I am happy that you use the tool.
It could be a problem with the initial orientation and placement of your scan. Try to take a look at the section in the README file on: "Specifying a pre-transformation"
You can experiment with different angles and see if your results get better.
Best,
Rasmus

**Comment by Nibenitez** [comment]
Thanks Rasmus for your prompt reply and guidance!
I tried different angles but still without better results. I checked in Meshlab the orientation and I have the mesh over the z and x axis. 
I will keep trying, but I would appreciate any other recomendation, maybe I missing something else.

![image](https://github.com/RasmusRPaulsen/Deep-MVLM/assets/51408311/a177cd1e-6234-4384-9286-d557dca94ddf)


![image](https://github.com/RasmusRPaulsen/Deep-MVLM/assets/51408311/8ca30be4-bb04-4ee1-862b-12f2c4829e87)

**Comment by RasmusRPaulsen** [comment]
Could you send the scan to me? Then I can see what might be the problem.

**Comment by Nibenitez** [comment]
> Could you send the scan to me? Then I can see what might be the problem.

[1_0_hrn_high_mesh.zip](https://github.com/RasmusRPaulsen/Deep-MVLM/files/12266935/1_0_hrn_high_mesh.zip)

Thank you! I have many of them to detect landmarks and your tool will be very usefull!

**Comment by RasmusRPaulsen** [comment]
I made it work by changing the scale=100 in the pre-align section of the JSON config file.

It is currently assumed that the face are recorded in physical space (in millimeters).  For non-calibrated 3D scanners, it is (unfortunately) necessary to scale the scan so it is approximately the same size as a real face (in mm).

![1face](https://github.com/RasmusRPaulsen/Deep-MVLM/assets/14818460/6007dd84-7e89-4c3e-a599-c8d29ae9eeea)

**Comment by Nibenitez** [comment]
Wow! Thank you Rasmus! I am getting great results now by changing the scale=100 per your comment.
Another last question, I am trying to evaluate meshes predicted by different facial reconstruction methods versus my own scans, and to obtein any metric about the quality of the reconstruction. I am using the following code: https://github.com/patrikhuber/fg2018-competition. In this code, is a requirement to have 7 landmarks:

![image](https://github.com/RasmusRPaulsen/Deep-MVLM/assets/51408311/e9cf95a0-1734-4722-857e-c06e8bf7dc38)


Is it possible to change the output of the .txt file with those only 7 landmarks instead of 84? So, I can use it in the evaluation algorithm. It is just a question, I know that probably the model was trained to detect more landmarks. Otherwise I can code a python script to get a .txt with only the 7 key points from the 84 txt file.

Thank you again for your time and for sharing your great work!

**Comment by RasmusRPaulsen** [comment]
I am happy that it works. I think it would be the easiest that you create a separate script that filters the landmarks from 84 to 7.
