### ISSUE TITLE
Any recommendations for how I can improve the accuracy of the landmarking for my usecase?

### ISSUE THREAD

**Issue by m-a-x-c** [RasmusRPaulsen/Deep-MVLM#13]
I am converting point cloud into mesh using Poison Reconstruction then applying the Deep-MVLM model. Any recommendations for how I can improve the accuracy of the landmarking?
![image](https://github.com/RasmusRPaulsen/Deep-MVLM/assets/35903396/536acfc3-41a7-41e4-b451-f2e9dee56960)

The 3D model from the above image:
[point_cloud_recon2.zip](https://github.com/RasmusRPaulsen/Deep-MVLM/files/15006347/point_cloud_recon2.zip)
Note that I have set "align_center_of_mass" and "write_pre_aligned" to true.

**Comment by mehraanc** [comment]
Answering my own question: the accuracy drastically improves when the color data is removed.

![image](https://github.com/RasmusRPaulsen/Deep-MVLM/assets/35903396/19e49d70-f684-4096-bfb9-af20356a0754)
