### ISSUE TITLE
White Image View

### ISSUE THREAD

**Issue by fuziwang** [RasmusRPaulsen/Deep-MVLM#5]
Hello, may I ask, if I test my own data, I find that first of all, my .obj file has vn, while the test data does not, will this affect? I also find that when I import the data into the model, the generated views are all white images. What is the reason? Thank you very much for your answer

**Comment by fuziwang** [comment]
Thank you very much. I found the problem because I did not put the point cloud data in the center of the coordinate. Could you please tell me how I can put my .obj file in the center through the Python code?

**Comment by jacobuu** [comment]
Hello ! 
We had kind of the same problem. Notice that the 3D file that the script is expecting is a .wrl (Vermal) file, so if you're using a .obj file (like I did) you need to change the vtkVRMLImporter() in vtkOBJImporter(). You can keep all the correlated method calls as they are.

**Comment by fuziwang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by ZhangYH-999** [comment]
Hello, may I ask, if just have .ply files, and don't know which kind of config files I should use. I had tried most of config files, but it still didn't work, and it showed 'No cells to subdivide'. Do you know how to solve this problem? Thanks
