### ISSUE TITLE
Implementation of 3D landmark annotation

### ISSUE THREAD

**Issue by Bornblack** [RasmusRPaulsen/Deep-MVLM#7]
Hi,
Can you share the implementation of 3D landmark annotation of DTU3D ?
The orignal annotation of BU-3DFE dataset seems unsatisfactory and does not provide the annotation of the nose tip that your annotation does.

Any help would be appreciate !

**Comment by RasmusRPaulsen** [comment]
Hi,
Due to GDPR issues, it is extremely difficult to share facial scans.
