### ISSUE TITLE
Is it able to support the xyz format file?

### ISSUE THREAD

**Issue by suijunqiang** [RasmusRPaulsen/Deep-MVLM#8]
First of all, thanks to share your great 3D face landmark project.
I am trying to recognize a face from a .xyz  cloud point data file, however you support OBJ/WRL/VTK/PLY only, because I am using a TOF sensor and able to capture xyz data only.
So would you please help me to make sure the xyz format able to support in your project.

Thanks & Best Regards
Sui

**Comment by RasmusRPaulsen** [comment]
Hi,
Sorry for the late answer. We normally require triangulated surfaces as input. You might try to do a surface reconstruction before using the Deep-MVLM framework. For example the Poisson surface reconstruction or the Markov Random Field surface reconstruction toolkit.

**Comment by suijunqiang** [comment]
Anyway, thanks so much.
I have figured a easy way out, really thanks again.

Thanks & Best Regards
Sui
